#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "adtBFS.c"

task main()
{
	if (getColorName(colorSensor) == colorBlue){
			forward(300,milliseconds,10);  // sudah berada di start
			backward(300,milliseconds,10);

			// Cari jalan
			SolveBFS();

	} else { // Belum berada di start
			Start();
			SolveBFS();
	}

	eraseDisplay();
	if (found_end == 1) {
			displayTextLine(2, "Solusi ditemukan");
			displayTextLine(5, "DONE");
	} else {
			displayTextLine(2, "Solusi tidak ditemukan");
	}

}

/*
	ALGORITMA KASAR

	idx = 0;
	banyaknextline = 1;
	state = LineFollow();
	while (state != 0 && state != 1) {
			if (state == 2) { //detect Hijau
					idx++;
					m[idx].isMaster = 1;

					getSimpang(m[idx]);			//cari banyaknya jalur pada simpangan ke-idx

					counter = 1;
					fix_idx = idx;
					while (counter <= banyaknextline) {
							gtn = gotonextline(m[idx]);		//pilih jalur dengan sudut terkecil

							if (gtn != 0) {
									state = LineFollow();		//jalan menurut jalur yang dipilih pada gtn

									if (counter == banyaknextline) {
											if (state == 2) {
													fix_idx++;
													getSimpang(m[fix_idx]);
													backtrack();
											}
									} else {
											if (state == 2) {
													idx++;
													getSimpang(m[idx]);
													fix_idx = idx;
											}
											counter++;
									}
							} else {
									i = 1;
									int buff;
									while (idx >= 1 && gotonextline(m[idx]) == 0) {
											buff = idx;
											backtrack();
											idx--;

									}
									//ulangi proses yang sama
									if (buff == 1) {
											banyaknextline++;
											counter = 1;
											idx = 1;
											fix_idx = 1;
											//reinisiasi arrDG
									}
							}
					}


			}
	}
*/
