#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "adtDFS.c"

task main()
{
	if (getColorName(colorSensor) == colorBlue){
			forward(300,milliseconds,10);  // sudah berada di start
			backward(300,milliseconds,10);

			// Cari jalan
			SolveDFS();

	} else { // Belum berada di start
			Start();
			SolveDFS();
	}

	eraseDisplay();

	if (found_end == 1) {
			displayTextLine(2, "Solusi ditemukan");
			displayTextLine(3, "DONE");
	} else {
			displayTextLine(2, "Solusi tidak ditemukan");
	}
}
